# Generated by Django 4.2.1 on 2023-05-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('maker', models.CharField(max_length=10, verbose_name='Производитель')),
                ('model', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Модель')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('model', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT,
                                            to='app_orm_trainer.product', verbose_name='Модель')),
                ('color', models.CharField(max_length=1, verbose_name='Цвет')),
                ('type', models.CharField(max_length=10, verbose_name='Тип')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('model', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT,
                                            to='app_orm_trainer.product', verbose_name='Модель')),
                ('speed', models.SmallIntegerField(verbose_name='Скорость')),
                ('ram', models.SmallIntegerField(verbose_name='Память')),
                ('hd', models.SmallIntegerField(verbose_name='Жесткий')),
                ('cd', models.CharField(max_length=10, verbose_name='привод')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('model', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT,
                                            to='app_orm_trainer.product', verbose_name='Модель')),

                ('speed', models.SmallIntegerField(verbose_name='Скорость')),
                ('ram', models.SmallIntegerField(verbose_name='Память')),
                ('hd', models.SmallIntegerField(verbose_name='Жесткий')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
                ('screen', models.SmallIntegerField(verbose_name='Экран')),
            ],
        ),
    ]

    initial = True

    dependencies = [
    ]

